# Generated by Django 5.2.6 on 2025-10-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'System Admin'), ('ma', 'Management Assistant')], default='ma', max_length=10),
        ),
    ]
