@startuml
left to right direction
skinparam packageStyle rectangle

actor "System Admin" as Admin
actor "Management Assistant" as MA

rectangle "University Cleaning System" {
  (Login) as Login
  (Create MA Accounts) as CMA
  (Create Zone) as CZ
  (Add a Building) as AB
  (Create Division) as CD
  (Create Schedule) as CS
  (Fill & Submit Schedule) as FSS
  (Review, Summarize, Approve Report) as RSAR
  (View & Download Summarized Report) as VDSR
  (Open and Close Submission) as OCS
}

Admin --> Login
Admin --> CMA
Admin --> CZ
Admin --> AB
Admin --> CD
Admin --> CS
Admin --> RSAR
Admin --> VDSR
Admin --> OCS

MA --> Login
MA --> FSS
MA --> VDSR

CZ --> AB : <<include>>
AB --> CD : <<include>>
@enduml
